services:
  db:
    image: postgres:16
    container_name: pr_review_test_db
    environment:
      POSTGRES_DB: pr_review_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass

    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - test_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d pr_review_test"]
      interval: 1s
      timeout: 3s
      retries: 10
      start_period: 2s

volumes:
  test_pgdata: