basePath: /
definitions:
  dto.CreatePullRequestRequest:
    properties:
      author_id:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
    required:
    - author_id
    - pull_request_id
    - pull_request_name
    type: object
  dto.MergePullRequestRequest:
    properties:
      pull_request_id:
        type: string
    required:
    - pull_request_id
    type: object
  dto.ReassignReviewerRequest:
    properties:
      old_reviewer_id:
        type: string
      pull_request_id:
        type: string
    required:
    - old_reviewer_id
    - pull_request_id
    type: object
  dto.SetUserActiveRequest:
    properties:
      is_active:
        type: boolean
      user_id:
        type: string
    required:
    - user_id
    type: object
  errors.ErrorResponse:
    properties:
      error:
        properties:
          code:
            type: string
          message:
            type: string
        type: object
    type: object
  handler.HealthResponse:
    properties:
      service:
        example: PR Reviewer Assignment Service
        type: string
      status:
        example: healthy
        type: string
      timestamp:
        example: "2025-11-25T16:30:45Z"
        type: string
    type: object
  handler.MassDeactivationRequest:
    properties:
      exclude_user_ids:
        example:
        - u1
        - u2
        items:
          type: string
        type: array
      team_name:
        example: backend
        type: string
    type: object
  handler.MassDeactivationResponse:
    properties:
      deactivated_users:
        example: 5
        type: integer
      failed_prs:
        example:
        - pr-1001
        items:
          type: string
        type: array
      processing_time_ms:
        example: 85
        type: integer
      updated_prs:
        example: 3
        type: integer
    type: object
  handler.OverallStatsResponse:
    properties:
      stats:
        properties:
          active_users:
            example: 12
            type: integer
          avg_reviews_per_pr:
            example: 2
            type: number
          merged_prs:
            example: 3
            type: integer
          open_prs:
            example: 7
            type: integer
          total_prs:
            example: 10
            type: integer
          total_reviews:
            example: 20
            type: integer
          total_users:
            example: 15
            type: integer
        type: object
    type: object
  handler.PRReviewStatsResponse:
    properties:
      stats:
        items:
          properties:
            author_id:
              example: u1
              type: string
            pr_id:
              example: pr-1001
              type: string
            pr_name:
              example: Add search feature
              type: string
            reviewer_count:
              example: 2
              type: integer
            status:
              example: OPEN
              type: string
          type: object
        type: array
    type: object
  handler.UserReviewStatsResponse:
    properties:
      stats:
        items:
          properties:
            review_count:
              example: 5
              type: integer
            team_name:
              example: backend
              type: string
            user_id:
              example: u1
              type: string
            username:
              example: Alice
              type: string
          type: object
        type: array
    type: object
  models.PullRequest:
    properties:
      assigned_reviewers:
        items:
          type: string
        type: array
      author_id:
        type: string
      createdAt:
        type: string
      mergedAt:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
      status:
        type: string
    type: object
  models.PullRequestShort:
    properties:
      author_id:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
      status:
        type: string
    type: object
  models.ReassignResponse:
    properties:
      pr:
        $ref: '#/definitions/models.PullRequest'
      replaced_by:
        type: string
    type: object
  models.Team:
    properties:
      members:
        items:
          $ref: '#/definitions/models.TeamMember'
        type: array
      team_name:
        type: string
    type: object
  models.TeamMember:
    properties:
      is_active:
        type: boolean
      user_id:
        type: string
      username:
        type: string
    type: object
  models.UserReviewResponse:
    properties:
      pull_requests:
        items:
          $ref: '#/definitions/models.PullRequestShort'
        type: array
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис автоматического назначения ревьюверов для Pull Request'ов
  title: PR Reviewer Assignment Service
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Возвращает статус сервиса
      produces:
      - application/json
      responses:
        "200":
          description: Статус сервиса
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: Проверка здоровья
      tags:
      - Health
  /pullRequest/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные PR
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreatePullRequestRequest'
      produces:
      - application/json
      responses:
        "201":
          description: PR создан
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Автор/команда не найдены
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "409":
          description: PR уже существует
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      tags:
      - PullRequests
  /pullRequest/merge:
    post:
      consumes:
      - application/json
      description: Идемпотентная операция мержа PR
      parameters:
      - description: Данные PR
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.MergePullRequestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: PR в состоянии MERGED
          schema:
            $ref: '#/definitions/models.PullRequest'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: PR не найден
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Пометить PR как MERGED
      tags:
      - PullRequests
  /pullRequest/reassign:
    post:
      consumes:
      - application/json
      description: Заменяет ревьювера на другого из его команды
      parameters:
      - description: Данные для переназначения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ReassignReviewerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Переназначение выполнено
          schema:
            $ref: '#/definitions/models.ReassignResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: PR или пользователь не найден
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "409":
          description: Нарушение доменных правил
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Переназначить конкретного ревьювера
      tags:
      - PullRequests
  /stats/overall:
    get:
      consumes:
      - application/json
      description: Возвращает общую статистику системы
      produces:
      - application/json
      responses:
        "200":
          description: Общая статистика
          schema:
            $ref: '#/definitions/handler.OverallStatsResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Получить общую статистику
      tags:
      - Statistics
  /stats/prs:
    get:
      consumes:
      - application/json
      description: Возвращает количество ревьюверов по каждому PR
      produces:
      - application/json
      responses:
        "200":
          description: Статистика по PR
          schema:
            $ref: '#/definitions/handler.PRReviewStatsResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Получить статистику по PR
      tags:
      - Statistics
  /stats/users:
    get:
      consumes:
      - application/json
      description: Возвращает количество назначений по каждому пользователю
      produces:
      - application/json
      responses:
        "200":
          description: Статистика по пользователям
          schema:
            $ref: '#/definitions/handler.UserReviewStatsResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Получить статистику по ревьюверам
      tags:
      - Statistics
  /team/add:
    post:
      consumes:
      - application/json
      description: Создает команду и обновляет/создает пользователей
      parameters:
      - description: Данные команды
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Team'
      produces:
      - application/json
      responses:
        "201":
          description: Команда создана
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Команда уже существует
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Создать команду с участниками
      tags:
      - Teams
  /team/get:
    get:
      consumes:
      - application/json
      description: Возвращает команду по имени
      parameters:
      - description: Уникальное имя команды
        in: query
        name: team_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Объект команды
          schema:
            $ref: '#/definitions/models.Team'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Команда не найдена
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Получить команду с участниками
      tags:
      - Teams
  /users/getReview:
    get:
      consumes:
      - application/json
      description: Возвращает список PR для ревью пользователя
      parameters:
      - description: Идентификатор пользователя
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список PR'ов пользователя
          schema:
            $ref: '#/definitions/models.UserReviewResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Получить PR'ы, где пользователь назначен ревьювером
      tags:
      - Users
  /users/massDeactivate:
    post:
      consumes:
      - application/json
      description: Деактивирует всех пользователей команды и безопасно переназначает
        ревьюверов открытых PR
      parameters:
      - description: Данные для массовой деактивации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.MassDeactivationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Результат массовой деактивации
          schema:
            $ref: '#/definitions/handler.MassDeactivationResponse'
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Команда не найдена
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Массовая деактивация пользователей команды
      tags:
      - Users
  /users/setIsActive:
    post:
      consumes:
      - application/json
      description: Обновляет активность пользователя
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.SetUserActiveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Обновлённый пользователь
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Неверный запрос
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/errors.ErrorResponse'
      summary: Установить флаг активности пользователя
      tags:
      - Users
swagger: "2.0"
